slogo_team05: Package simulationObjects
Package simulationObjects
Classes
class Pen
class Point
class SLogoLine
class TurtleList
class UpdateLocation
Functions
Turtle ()
Turtle (Turtle turtle)
boolean getVisible ()
void setPosition (double x, double y)
void setPosition (Point position)
Point getPosition ()
double getRotation ()
void setRotation (double rotation)
Turtle getTurtle ()
void setVisible (boolean b)
Pen getPen ()
int getIdNum ()
void setIdNum (int idNum)
Variables
<<<<<<< HEADpublicclassTurtleextendsUpdateLocation{=======publicclassTurtle{>>>>>> Steven Point position = new Point(400, 300)
double rotation = 90
boolean visible = true
Pen myPen
int idNum
Function Documentation
int simulationObjects.getIdNum ()
Returns
id of current turtle
Definition at line 138 of file Turtle.java.
References idNum.
Pen simulationObjects.getPen ()
Returns
pen of the turtle
Definition at line 130 of file Turtle.java.
References myPen.
Point simulationObjects.getPosition ()
get the current position of the turtle.
Returns
Point the turtle location within the x, y coordinate system
See also
Point
Definition at line 76 of file Turtle.java.
References position.
double simulationObjects.getRotation ()
Get the rotation of the turtle.
Returns
double the rotation of the turtle
Definition at line 85 of file Turtle.java.
References rotation.
Turtle simulationObjects.getTurtle ()
Returns
current turtle
Definition at line 111 of file Turtle.java.
boolean simulationObjects.getVisible ()
Definition at line 42 of file Turtle.java.
References visible.
void simulationObjects.setIdNum (int idNum)
set the idnum of the turtle
Parameters
idNum
Definition at line 147 of file Turtle.java.
References idNum.
void simulationObjects.setPosition (double x, double y)
Set the position within an x, y coordinate system.
Parameters
x a double representing the x-coordinate of the turtle
y a double representing the y-coordinate of the turtle
Definition at line 54 of file Turtle.java.
References simulationObjects.Point.x, and simulationObjects.Point.y.
void simulationObjects.setPosition (Point position)
Set the position within an x, y coordinate system.
Parameters
position a Point object representing the position of the turtle
See also
Point
Definition at line 66 of file Turtle.java.
References position.
void simulationObjects.setRotation (double rotation)
Set the rotation of the turtle. Input outside of [0, 360] will be set to an equivalent angle within [0, 360].
Parameters
rotation a double representing the rotation of the turtle.
Definition at line 96 of file Turtle.java.
References rotation.
void simulationObjects.setVisible (boolean b)
Parameters
visibility of turtle
Definition at line 122 of file Turtle.java.
simulationObjects.Turtle ()
Constructor
Definition at line 19 of file Turtle.java.
Referenced by simulationObjects.TurtleList.addStamp(), commands.CommandList.clearScreen(), simulationObjects.TurtleList.createTurtle(), commands.CommandList.forwardCommand(), controller.MainController.getTurtle(), commands.CommandList.heading(), commands.CommandList.hideTurtle(), commands.CommandList.penDown(), commands.CommandList.penDownP(), commands.CommandList.penUp(), commands.CommandList.setPenWidth(), commands.CommandList.SetXY(), commands.CommandList.showingP(), commands.CommandList.showTurtle(), commands.CommandList.towards(), commands.CommandList.turnCommand(), commands.CommandList.xCor(), and commands.CommandList.yCor().
simulationObjects.Turtle (Turtle turtle)
Copy-constructor
Parameters
turtle a Turtle object whose data will be copied to the new Turtle instance.
Definition at line 34 of file Turtle.java.
Variable Documentation
int simulationObjects.idNum
Definition at line 14 of file Turtle.java.
Referenced by getIdNum(), and setIdNum().
Pen simulationObjects.myPen
Definition at line 13 of file Turtle.java.
Referenced by getPen().
<<<<<<<HEADpublicclassTurtleextendsUpdateLocation{=======publicclassTurtle{>>>>>> Steven Point simulationObjects.position = new Point(400, 300)
Definition at line 10 of file Turtle.java.
Referenced by gui.GUIScene.draw(), getPosition(), and setPosition().
double simulationObjects.rotation = 90
Definition at line 11 of file Turtle.java.
Referenced by getRotation(), and setRotation().
boolean simulationObjects.visible = true
Definition at line 12 of file Turtle.java.
Referenced by getVisible().