slogo_team05: gui.GUIScene Class Reference
gui.GUIScene Class Reference
Public Member Functions
void createScene (Stage s) throws FileNotFoundException
Protected Attributes
TurtleView turtle = new TurtleView(new Image(getClass().getResourceAsStream("../images/turtle.png"), 80, 60, true, true))
String userCommand = new String()
Private Member Functions
void createGUI () throws FileNotFoundException
void draw ()
MenuBar getTopToolBar ()
GridPane getRightBox ()
Group addGrid () throws FileNotFoundException
FlowPane addButtons () throws FileNotFoundException
Image setImage (FileInputStream input)
void update ()
Static Private Member Functions
static String toRGBString (Color c)
Private Attributes
Locale[] supportedLocales = { new Locale("en", "US", "English"), new Locale("fr", "FR", "French")}
Text statusText = new Text()
GridPane playground = new GridPane()
MainController controller = new MainController()
ReadAndWrite saver = new ReadAndWrite()
BorderPane layout = new BorderPane()
GridPane rightSide
FlowPane flow
MenuBar topToolBar = new MenuBar()
Group root
ResourceBundle guiText
Pen myPen
Scene slogo
Static Private Attributes
static double SCENE_WIDTH = 1280
static double SCENE_HEIGHT = 720
static double WRAP_LENGTH = 150
static double WRAP_HEIGHT = 720 / 4
static double HELP_WIDTH = 800
static double HELP_HEIGHT = 500
Detailed Description
Definition at line 47 of file GUIScene.java.
Member Function Documentation
FlowPane gui.GUIScene.addButtons () throws FileNotFoundException private
Definition at line 246 of file GUIScene.java.
References gui.Buttons.changeImage(), gui.Buttons.changeLang(), gui.GUIScene.createGUI(), gui.Buttons.factory(), gui.GUIScene.flow, simulationObjects.Pen.getColor(), simulationObjects.Pen.setActive(), simulationObjects.Pen.setColor(), gui.GUIScene.setImage(), simulationObjects.Pen.setStyle(), simulationObjects.Pen.setWidth(), and gui.GUIScene.toRGBString().
Referenced by gui.GUIScene.createGUI().
Group gui.GUIScene.addGrid () throws FileNotFoundException private
Definition at line 230 of file GUIScene.java.
References controller.MainController.getTurtle(), gui.GUIScene.root, view.TurtleView.setData(), and gui.GUIScene.update().
Referenced by gui.GUIScene.createGUI().
void gui.GUIScene.createGUI () throws FileNotFoundException private
Definition at line 89 of file GUIScene.java.
References gui.GUIScene.addButtons(), gui.GUIScene.addGrid(), gui.GUIScene.getRightBox(), gui.GUIScene.getTopToolBar(), controller.MainController.passInput(), and gui.GUIScene.update().
Referenced by gui.GUIScene.addButtons(), and gui.GUIScene.createScene().
void gui.GUIScene.createScene (Stage s) throws FileNotFoundException
Definition at line 77 of file GUIScene.java.
References gui.GUIScene.createGUI(), controller.MainController.getTurtle(), and view.TurtleView.setData().
Referenced by gui.GUIStart.start(), and controller.SLogoMain.start().
void gui.GUIScene.draw () private
Definition at line 113 of file GUIScene.java.
References simulationObjects.Pen.getActive(), simulationObjects.Pen.getColor(), simulationObjects.Pen.getStyle(), controller.MainController.getTurtle(), simulationObjects.Pen.getWidth(), simulationObjects.position, simulationObjects.Point.x, and simulationObjects.Point.y.
Referenced by gui.GUIScene.update().
GridPane gui.GUIScene.getRightBox () private
Definition at line 192 of file GUIScene.java.
References controller.MainController.getHistory(), controller.MainController.passInput(), gui.GUIScene.rightSide, gui.Buttons.status(), and gui.GUIScene.update().
Referenced by gui.GUIScene.createGUI().
MenuBar gui.GUIScene.getTopToolBar () private
Definition at line 134 of file GUIScene.java.
References gui.ReadAndWrite.read(), gui.GUIScene.topToolBar, and gui.ReadAndWrite.write().
Referenced by gui.GUIScene.createGUI().
Image gui.GUIScene.setImage (FileInputStream input) private
Definition at line 392 of file GUIScene.java.
Referenced by gui.GUIScene.addButtons().
static String gui.GUIScene.toRGBString (Color c) static private
Definition at line 384 of file GUIScene.java.
Referenced by gui.GUIScene.addButtons().
void gui.GUIScene.update () private
Definition at line 396 of file GUIScene.java.
References gui.GUIScene.draw(), controller.MainController.getTurtle(), and view.TurtleView.setData().
Referenced by gui.GUIScene.addGrid(), gui.GUIScene.createGUI(), and gui.GUIScene.getRightBox().
Member Data Documentation
MainController gui.GUIScene.controller = new MainController() private
Definition at line 59 of file GUIScene.java.
FlowPane gui.GUIScene.flow private
Definition at line 69 of file GUIScene.java.
Referenced by gui.GUIScene.addButtons().
ResourceBundle gui.GUIScene.guiText private
Definition at line 72 of file GUIScene.java.
double gui.GUIScene.HELP_HEIGHT = 500 static private
Definition at line 65 of file GUIScene.java.
double gui.GUIScene.HELP_WIDTH = 800 static private
Definition at line 64 of file GUIScene.java.
BorderPane gui.GUIScene.layout = new BorderPane() private
Definition at line 67 of file GUIScene.java.
Pen gui.GUIScene.myPen private
Definition at line 73 of file GUIScene.java.
GridPane gui.GUIScene.playground = new GridPane() private
Definition at line 58 of file GUIScene.java.
GridPane gui.GUIScene.rightSide private
Definition at line 68 of file GUIScene.java.
Referenced by gui.GUIScene.getRightBox().
Group gui.GUIScene.root private
Definition at line 71 of file GUIScene.java.
Referenced by gui.GUIScene.addGrid().
ReadAndWrite gui.GUIScene.saver = new ReadAndWrite() private
Definition at line 66 of file GUIScene.java.
double gui.GUIScene.SCENE_HEIGHT = 720 static private
Definition at line 61 of file GUIScene.java.
double gui.GUIScene.SCENE_WIDTH = 1280 static private
Definition at line 60 of file GUIScene.java.
Scene gui.GUIScene.slogo private
Definition at line 74 of file GUIScene.java.
Text gui.GUIScene.statusText = new Text() private
Definition at line 55 of file GUIScene.java.
Locale [] gui.GUIScene.supportedLocales = { new Locale("en", "US", "English"), new Locale("fr", "FR", "French")} private
Application scene is managed in this class
Author
Steven Pierre
Kevin Rhine cellsociety_team15
Definition at line 54 of file GUIScene.java.
MenuBar gui.GUIScene.topToolBar = new MenuBar() private
Definition at line 70 of file GUIScene.java.
Referenced by gui.GUIScene.getTopToolBar().
TurtleView gui.GUIScene.turtle = new TurtleView(new Image(getClass().getResourceAsStream("../images/turtle.png"), 80, 60, true, true)) protected
Definition at line 56 of file GUIScene.java.
String gui.GUIScene.userCommand = new String() protected
Definition at line 57 of file GUIScene.java.
double gui.GUIScene.WRAP_HEIGHT = 720 / 4 static private
Definition at line 63 of file GUIScene.java.
double gui.GUIScene.WRAP_LENGTH = 150 static private
Definition at line 62 of file GUIScene.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/gui/GUIScene.java