slogo_team05: gui.Buttons Class Reference
gui.Buttons Class Reference
Static Public Member Functions
static String status (List< String > status)
static void changeLang ()
Static Protected Member Functions
static int factory (String value)
static void help ()
static String updateMovement (KeyEvent e)
static void changeImage (TurtleView turtle)
Static Private Attributes
static double HELP_WIDTH = 800
static double HELP_HEIGHT = 500
Detailed Description
Definition at line 19 of file Buttons.java.
Member Function Documentation
static void gui.Buttons.changeImage (TurtleView turtle) static protected
Definition at line 50 of file Buttons.java.
Referenced by gui.GUIScene.addButtons().
static void gui.Buttons.changeLang () static
Definition at line 70 of file Buttons.java.
Referenced by gui.GUIScene.addButtons().
static int gui.Buttons.factory (String value) static protected
Definition at line 23 of file Buttons.java.
Referenced by gui.GUIScene.addButtons().
static void gui.Buttons.help () static protected
Definition at line 29 of file Buttons.java.
static String gui.Buttons.status (List< String > status) static
Definition at line 62 of file Buttons.java.
Referenced by gui.GUIScene.getRightBox().
static String gui.Buttons.updateMovement (KeyEvent e) static protected
Definition at line 41 of file Buttons.java.
Member Data Documentation
double gui.Buttons.HELP_HEIGHT = 500 static private
Definition at line 21 of file Buttons.java.
double gui.Buttons.HELP_WIDTH = 800 static private
Definition at line 20 of file Buttons.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/gui/Buttons.java