slogo_team05: simulationObjects.Pen Class Reference
simulationObjects.Pen Class Reference
Public Member Functions
Pen ()
void setColor (Color color)
Color getColor ()
void setWidth (double width)
double getWidth ()
void setActive (boolean active)
boolean getActive ()
void setStyle (String sty)
String getStyle ()
Private Attributes
Color myColor
double myWidth
boolean active
String myStyle
Detailed Description
Definition at line 5 of file Pen.java.
Constructor & Destructor Documentation
simulationObjects.Pen.Pen ()
Definition at line 12 of file Pen.java.
Member Function Documentation
boolean simulationObjects.Pen.getActive ()
Definition at line 40 of file Pen.java.
References simulationObjects.Pen.active.
Referenced by gui.GUIScene.draw().
Color simulationObjects.Pen.getColor ()
Definition at line 24 of file Pen.java.
References simulationObjects.Pen.myColor.
Referenced by gui.GUIScene.addButtons(), and gui.GUIScene.draw().
String simulationObjects.Pen.getStyle ()
Definition at line 48 of file Pen.java.
References simulationObjects.Pen.myStyle.
Referenced by gui.GUIScene.draw().
double simulationObjects.Pen.getWidth ()
Definition at line 32 of file Pen.java.
References simulationObjects.Pen.myWidth.
Referenced by gui.GUIScene.draw().
void simulationObjects.Pen.setActive (boolean active)
Definition at line 36 of file Pen.java.
References simulationObjects.Pen.active.
Referenced by gui.GUIScene.addButtons().
void simulationObjects.Pen.setColor (Color color)
Definition at line 20 of file Pen.java.
Referenced by gui.GUIScene.addButtons().
void simulationObjects.Pen.setStyle (String sty)
Definition at line 44 of file Pen.java.
Referenced by gui.GUIScene.addButtons().
void simulationObjects.Pen.setWidth (double width)
Definition at line 28 of file Pen.java.
Referenced by gui.GUIScene.addButtons().
Member Data Documentation
boolean simulationObjects.Pen.active private
Definition at line 9 of file Pen.java.
Referenced by simulationObjects.Pen.getActive(), and simulationObjects.Pen.setActive().
Color simulationObjects.Pen.myColor private
Definition at line 7 of file Pen.java.
Referenced by simulationObjects.Pen.getColor().
String simulationObjects.Pen.myStyle private
Definition at line 10 of file Pen.java.
Referenced by simulationObjects.Pen.getStyle().
double simulationObjects.Pen.myWidth private
Definition at line 8 of file Pen.java.
Referenced by simulationObjects.Pen.getWidth().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/simulationObjects/Pen.java