slogo_team05: controller.MainController Class Reference
controller.MainController Class Reference
Public Member Functions
MainController ()
void passInput (String input) throws ParsingException, UnbalancedBracketsException
Turtle getTurtle ()
List< String > getHistory ()
Private Attributes
Compiler compiler = new Compiler()
Turtle turtle = new Turtle()
List< String > history = new ArrayList<String>()
Map< String, ArrayList< Command< Turtle, Void > > > cache = new HashMap<String, ArrayList<Command<Turtle, Void>>>()
Detailed Description
Definition at line 16 of file MainController.java.
Constructor & Destructor Documentation
controller.MainController.MainController ()
Definition at line 23 of file MainController.java.
Member Function Documentation
List<String> controller.MainController.getHistory ()
Definition at line 44 of file MainController.java.
References controller.MainController.history.
Referenced by gui.GUIScene.getRightBox().
Turtle controller.MainController.getTurtle ()
Definition at line 40 of file MainController.java.
References simulationObjects.Turtle().
Referenced by gui.GUIScene.addGrid(), gui.GUIScene.createScene(), gui.GUIScene.draw(), JUnitTest.BackendAPITest.testPos(), and gui.GUIScene.update().
void controller.MainController.passInput (String input) throws ParsingException, UnbalancedBracketsException
Definition at line 27 of file MainController.java.
References compiler.Compiler.compile().
Referenced by gui.GUIScene.createGUI(), gui.GUIScene.getRightBox(), and JUnitTest.BackendAPITest.test().
Member Data Documentation
Map<String, ArrayList<Command<Turtle, Void> > > controller.MainController.cache = new HashMap<String, ArrayList<Command<Turtle, Void>>>() private
Definition at line 21 of file MainController.java.
Compiler controller.MainController.compiler = new Compiler() private
Definition at line 17 of file MainController.java.
List<String> controller.MainController.history = new ArrayList<String>() private
Definition at line 19 of file MainController.java.
Referenced by controller.MainController.getHistory().
Turtle controller.MainController.turtle = new Turtle() private
Definition at line 18 of file MainController.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/controller/MainController.java