slogo_team05: compiler.ParseTable Class Reference
compiler.ParseTable Class Reference
Public Member Functions
String[] getLHS ()
ArrayList< HashMap< String, Integer > > getNextState ()
ArrayList< HashMap< String, String > > getOperation ()
int[] getRHS ()
void initializeTable ()
Static Private Attributes
static ArrayList< HashMap< String, String > > myOperation = new ArrayList<>()
static ArrayList< HashMap< String, Integer > > nextState = new ArrayList<>()
static String[] key = new String[82]
static String[] myLHS = new String[78]
static int[] myRHS = new int[78]
Detailed Description
Definition at line 10 of file ParseTable.java.
Member Function Documentation
String [] compiler.ParseTable.getLHS ()
left hand side of rules
Returns
Definition at line 23 of file ParseTable.java.
References compiler.ParseTable.myLHS.
Referenced by compiler.Compiler.initialize().
ArrayList<HashMap<String, Integer> > compiler.ParseTable.getNextState ()
getter for next state
Returns
list of next state
Definition at line 33 of file ParseTable.java.
References compiler.ParseTable.nextState.
Referenced by compiler.Compiler.initialize().
ArrayList<HashMap<String, String> > compiler.ParseTable.getOperation ()
getter for next operation
Returns
list of next ops
Definition at line 43 of file ParseTable.java.
References compiler.ParseTable.myOperation.
Referenced by compiler.Compiler.initialize().
int [] compiler.ParseTable.getRHS ()
right hand side of rules
Returns
Definition at line 54 of file ParseTable.java.
References compiler.ParseTable.myRHS.
Referenced by compiler.Compiler.initialize().
void compiler.ParseTable.initializeTable ()
create parse table for parsing
Definition at line 63 of file ParseTable.java.
Referenced by compiler.Compiler.initialize().
Member Data Documentation
String [] compiler.ParseTable.key = new String[82] static private
Definition at line 13 of file ParseTable.java.
String [] compiler.ParseTable.myLHS = new String[78] static private
Definition at line 14 of file ParseTable.java.
Referenced by compiler.ParseTable.getLHS().
ArrayList<HashMap<String, String> > compiler.ParseTable.myOperation = new ArrayList<>() static private
Definition at line 11 of file ParseTable.java.
Referenced by compiler.ParseTable.getOperation().
int [] compiler.ParseTable.myRHS = new int[78] static private
Definition at line 15 of file ParseTable.java.
Referenced by compiler.ParseTable.getRHS().
ArrayList<HashMap<String, Integer> > compiler.ParseTable.nextState = new ArrayList<>() static private
Definition at line 12 of file ParseTable.java.
Referenced by compiler.ParseTable.getNextState().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/compiler/ParseTable.java