slogo_team05: compiler.Compiler Class Reference
compiler.Compiler Class Reference
Public Member Functions
Compiler ()
ArrayList< Command< Turtle, Void > > compile (String input) throws ParsingException
List< SymbolTableEntry > getSymbolTable ()
Static Public Member Functions
static void main (String[] args) throws Exception
Public Attributes
ArrayList< HashMap< String, String > > move = new ArrayList<>()
ArrayList< HashMap< String, Integer > > nextState = new ArrayList<>()
Package Attributes
Stack< Integer > state = new Stack<Integer>()
Stack< String > symbol = new Stack<String>()
Private Member Functions
void initGrammar ()
void initialize ()
Stack< Integer > interpreter (String input) throws ParsingException
String scanner (String inputBuffer) throws ParsingException
void symbolTableGeneration (String[] split, Type[] tokens)
String translateToEnglish (String inputBuffer)
Private Attributes
ParseTable myParseTable = new ParseTable()
HashMap< String, String > grammar = new HashMap<>()
HashMap< String, String > dictionary = new HashMap<>()
String[] lhs = new String[61]
int[] rhs
String language = ""
Static Private Attributes
static List< SymbolTableEntry > symbolTable = new ArrayList<>()
Detailed Description
Definition at line 20 of file Compiler.java.
Constructor & Destructor Documentation
compiler.Compiler.Compiler ()
Definition at line 40 of file Compiler.java.
Referenced by compiler.Compiler.main().
Member Function Documentation
ArrayList<Command<Turtle, Void> > compiler.Compiler.compile (String input) throws ParsingException
take the input passed from MainController and compile the input program
Parameters
input
Returns
Exceptions
ParsingException
Definition at line 53 of file Compiler.java.
References compiler.AST.generate(), compiler.Compiler.initialize(), compiler.Compiler.interpreter(), compiler.Compiler.scanner(), and compiler.AST.traverse().
Referenced by compiler.Compiler.main(), controller.MainController.passInput(), JUnitTest.CompilerTest.testGrammarException(), and JUnitTest.CompilerTest.testSyntaxException().
List<SymbolTableEntry> compiler.Compiler.getSymbolTable ()
getter for symboltable
Returns
created symbol table
Definition at line 86 of file Compiler.java.
References compiler.Compiler.symbolTable.
Referenced by compiler.AST.generate().
void compiler.Compiler.initGrammar () private
initialize the dictionaries for translation
Definition at line 94 of file Compiler.java.
Referenced by compiler.Compiler.initialize().
void compiler.Compiler.initialize () private
initilize tables needed for parsing
Definition at line 133 of file Compiler.java.
References compiler.ParseTable.getLHS(), compiler.ParseTable.getNextState(), compiler.ParseTable.getOperation(), compiler.ParseTable.getRHS(), compiler.Compiler.initGrammar(), and compiler.ParseTable.initializeTable().
Referenced by compiler.Compiler.compile().
Stack<Integer> compiler.Compiler.interpreter (String input) throws ParsingException private
Use the modified inputBuffer to construct a derivation list to get the program
Parameters
String modified inputBuffer
Returns
Stack<Integer> derivation Rules
Exceptions
ParsingException
Definition at line 153 of file Compiler.java.
Referenced by compiler.Compiler.compile().
static void compiler.Compiler.main (String[] args) throws Exception static
Definition at line 21 of file Compiler.java.
References compiler.Compiler.compile(), and compiler.Compiler.Compiler().
String compiler.Compiler.scanner (String inputBuffer) throws ParsingException private
Parameters
inputBuffer
Returns
Exceptions
ParsingException
Definition at line 222 of file Compiler.java.
References compiler.TokenFinder.Type.CONSTANT, compiler.Compiler.symbolTableGeneration(), compiler.TokenFinder.tokenize(), compiler.Compiler.translateToEnglish(), and compiler.TokenFinder.Type.VARIABLE.
Referenced by compiler.Compiler.compile().
void compiler.Compiler.symbolTableGeneration (String[] split, Type[] tokens) private
create a symboltable to hold constants and variables
Parameters
split
tokens
Definition at line 257 of file Compiler.java.
References compiler.SymbolTableEntry.setName(), compiler.SymbolTableEntry.setType(), and compiler.SymbolTableEntry.setValue().
Referenced by compiler.Compiler.scanner().
String compiler.Compiler.translateToEnglish (String inputBuffer) private
take the input buffer and translate to english based on the dictionary
Parameters
inputBuffer
Returns
Definition at line 287 of file Compiler.java.
Referenced by compiler.Compiler.scanner().
Member Data Documentation
HashMap<String, String> compiler.Compiler.dictionary = new HashMap<>() private
Definition at line 32 of file Compiler.java.
HashMap<String, String> compiler.Compiler.grammar = new HashMap<>() private
Definition at line 31 of file Compiler.java.
String compiler.Compiler.language = "" private
Definition at line 38 of file Compiler.java.
String [] compiler.Compiler.lhs = new String[61] private
Definition at line 36 of file Compiler.java.
ArrayList<HashMap<String, String> > compiler.Compiler.move = new ArrayList<>()
Definition at line 28 of file Compiler.java.
ParseTable compiler.Compiler.myParseTable = new ParseTable() private
Definition at line 27 of file Compiler.java.
ArrayList<HashMap<String, Integer> > compiler.Compiler.nextState = new ArrayList<>()
Definition at line 29 of file Compiler.java.
int [] compiler.Compiler.rhs private
Definition at line 37 of file Compiler.java.
Stack<Integer> compiler.Compiler.state = new Stack<Integer>() package
Definition at line 34 of file Compiler.java.
Stack<String> compiler.Compiler.symbol = new Stack<String>() package
Definition at line 35 of file Compiler.java.
List<SymbolTableEntry> compiler.Compiler.symbolTable = new ArrayList<>() static private
Definition at line 30 of file Compiler.java.
Referenced by compiler.Compiler.getSymbolTable().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/compiler/Compiler.java