slogo_team05: commands.CommandList Class Reference
commands.CommandList Class Reference
Static Public Member Functions
static Command< Turtle, Void > forwardCommand (final double forwardBy)
static Command< Turtle, Void > turnCommand (final double clockwiseDegrees)
static Command< Turtle, Void > SetXY (final double val1, final double val2)
static Command< Turtle, Void > towards (final double val1, final double val2)
static Command< Turtle, Void > clearScreen ()
static Command< Turtle, Void > xCor ()
static Command< Turtle, Void > yCor ()
static Command< Turtle, Void > heading ()
static Command< Turtle, Void > penDownP ()
static Command< Turtle, Void > showingP ()
static Command< Turtle, Void > penDown ()
static Command< Turtle, Void > penUp ()
static Command< Turtle, Void > showTurtle ()
static Command< Turtle, Void > hideTurtle ()
static Command< Turtle, Void > setPenWidth (final double val)
Detailed Description
Definition at line 6 of file CommandList.java.
Member Function Documentation
static Command<Turtle, Void> commands.CommandList.clearScreen () static
clear the screen return the turtle to original position
Returns
Definition at line 113 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.forwardCommand (final double forwardBy) static
the FD and BK command
Parameters
forwardBy
Returns
the distance travelled
Definition at line 15 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.heading () static
heading query
Returns
Definition at line 170 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.hideTurtle () static
hide turtle
Returns
Definition at line 269 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.penDown () static
set pen down
Returns
Definition at line 217 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.penDownP () static
pen up query
Returns
Definition at line 185 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.penUp () static
set pen up
Returns
Definition at line 234 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.setPenWidth (final double val) static
set pen width to val
Parameters
val
Returns
Definition at line 287 of file CommandList.java.
References simulationObjects.Turtle().
static Command<Turtle, Void> commands.CommandList.SetXY (final double val1, final double val2) static
set the turtle location
Parameters
x
y
Returns
distance moved
Definition at line 59 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.showingP () static
visible query
Returns
Definition at line 201 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.showTurtle () static
show turtle
Returns
Definition at line 251 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.towards (final double val1, final double val2) static
turn the turtle towards a point
Parameters
x
y
Returns
resulted rotation
Definition at line 87 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.turnCommand (final double clockwiseDegrees) static
the LT and RT command
Parameters
clockwiseDegrees
Returns
the resulted rotation string
Definition at line 40 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.xCor () static
Xcor query
Returns
Definition at line 138 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
static Command<Turtle, Void> commands.CommandList.yCor () static
yCor query
Returns
Definition at line 155 of file CommandList.java.
References simulationObjects.Turtle().
Referenced by compiler.AST.traverse().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/commands/CommandList.java