slogo_team05: compiler.AST Class Reference
compiler.AST Class Reference
Public Member Functions
ArrayList< Command< Turtle, Void > > traverse (Node currentNode, ArrayList< Command< Turtle, Void >> ret)
Package Functions
Node generate (Stack< Integer > sequence)
Private Attributes
Stack< Node > syntaxTree = new Stack<Node>()
List< SymbolTableEntry > symbolTable = new ArrayList<>()
Detailed Description
Definition at line 12 of file AST.java.
Member Function Documentation
Node compiler.AST.generate (Stack< Integer > sequence) package
generate syntax tree with the rules provided
Parameters
sequence
Definition at line 23 of file AST.java.
References compiler.Node.data_1, and compiler.Compiler.getSymbolTable().
Referenced by compiler.Compiler.compile().
ArrayList<Command<Turtle, Void> > compiler.AST.traverse (Node currentNode, ArrayList< Command< Turtle, Void >> ret)
Definition at line 168 of file AST.java.
References commands.CommandList.clearScreen(), compiler.Node.data_1, compiler.Node.data_2, compiler.Node.data_3, commands.CommandList.forwardCommand(), commands.CommandList.heading(), commands.CommandList.hideTurtle(), compiler.Node.left, commands.CommandList.penDown(), commands.CommandList.penDownP(), commands.CommandList.penUp(), compiler.Node.right, commands.CommandList.SetXY(), commands.CommandList.showingP(), commands.CommandList.showTurtle(), commands.CommandList.towards(), commands.CommandList.turnCommand(), compiler.Node.type, commands.CommandList.xCor(), and commands.CommandList.yCor().
Referenced by compiler.Compiler.compile().
Member Data Documentation
List<SymbolTableEntry> compiler.AST.symbolTable = new ArrayList<>() private
Definition at line 15 of file AST.java.
Stack<Node> compiler.AST.syntaxTree = new Stack<Node>() private
Definition at line 14 of file AST.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/compiler/AST.java