slogo_team05: compiler.TokenFinder Class Reference
compiler.TokenFinder Class Reference
Classes
enum Type
Static Public Member Functions
static Type stringType (String s)
static Type[] tokenize (String[] args)
Static Private Attributes
static ResourceBundle regExProperties
Detailed Description
Definition at line 6 of file TokenFinder.java.
Member Function Documentation
static Type compiler.TokenFinder.stringType (String s) static
defines the type of the string
Parameters
s
Returns
the type of the string
Definition at line 24 of file TokenFinder.java.
References compiler.TokenFinder.Type.COMMAND, compiler.TokenFinder.Type.CONSTANT, compiler.TokenFinder.Type.LIST_END, compiler.TokenFinder.Type.LIST_START, compiler.TokenFinder.Type.NOT_RECOGNIZED, compiler.TokenFinder.Type.PARENS_END, compiler.TokenFinder.Type.PARENS_START, and compiler.TokenFinder.Type.VARIABLE.
Referenced by compiler.TokenFinder.tokenize().
static Type [] compiler.TokenFinder.tokenize (String[] args) static
create the tokenize array of arguments where each argument is defined with a type
Parameters
args
Returns
an array of argument that has been defined with a type
Definition at line 52 of file TokenFinder.java.
References compiler.TokenFinder.stringType().
Referenced by compiler.Compiler.scanner().
Member Data Documentation
ResourceBundle compiler.TokenFinder.regExProperties static private
Definition at line 16 of file TokenFinder.java.
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/compiler/TokenFinder.java