slogo_team05: simulationObjects.TurtleList Class Reference
simulationObjects.TurtleList Class Reference
Public Member Functions
boolean addActiveTurtle (int index)
Turtle getTurtle (int index)
void removeTurtle (int index)
List< Turtle > getAllTurtles ()
List< Turtle > getActiveTurtles ()
boolean setActiveTurtles (int[] indexes)
int[] getActiveTurtleIndexes ()
void addStamp (Turtle t)
void clearStamps ()
List< Turtle > getStamps ()
int getTurtleIndex (Turtle t)
int findTurtle (Turtle t)
void clearActiveTurtles ()
void addTurtle (Turtle t)
Protected Member Functions
void init () throws Exception
Protected Attributes
List< Turtle > turtles
List< Turtle > activeTurtles
List< Turtle > stamps
Private Member Functions
Turtle createTurtle ()
Detailed Description
Definition at line 6 of file TurtleList.java.
Member Function Documentation
boolean simulationObjects.TurtleList.addActiveTurtle (int index)
add active turtle to a list
Parameters
index to add
Returns
if addition is successful
Definition at line 29 of file TurtleList.java.
Referenced by simulationObjects.TurtleList.init().
void simulationObjects.TurtleList.addStamp (Turtle t)
add a stamp of the current active turtle
Parameters
t
Definition at line 114 of file TurtleList.java.
References simulationObjects.Turtle().
void simulationObjects.TurtleList.addTurtle (Turtle t)
add a turtle to an active list of turtles
Parameters
turtle
Definition at line 175 of file TurtleList.java.
References simulationObjects.TurtleList.findTurtle().
void simulationObjects.TurtleList.clearActiveTurtles ()
clear the list of active turtles
Definition at line 166 of file TurtleList.java.
void simulationObjects.TurtleList.clearStamps ()
clear the list of stamps made
Definition at line 121 of file TurtleList.java.
Turtle simulationObjects.TurtleList.createTurtle () private
creates the turtle and added it to a list of turtles that has been created
Returns
the new turtle being created
Definition at line 196 of file TurtleList.java.
References simulationObjects.Turtle().
Referenced by simulationObjects.TurtleList.init().
int simulationObjects.TurtleList.findTurtle (Turtle t)
looks through list of turtles to see if the turtle t is in that list
Parameters
turtle
Returns
Index Identified Turtle
Definition at line 155 of file TurtleList.java.
Referenced by simulationObjects.TurtleList.addTurtle().
int [] simulationObjects.TurtleList.getActiveTurtleIndexes ()
get the indexes of all the active turtles in the active turtles list
Returns
indexes
Definition at line 101 of file TurtleList.java.
References simulationObjects.TurtleList.getTurtleIndex().
List<Turtle> simulationObjects.TurtleList.getActiveTurtles ()
get the active list of turtles
Returns
activeTurtlesList
Definition at line 72 of file TurtleList.java.
References simulationObjects.TurtleList.activeTurtles.
List<Turtle> simulationObjects.TurtleList.getAllTurtles ()
get the list of all the turtles that has been created by the user
Returns
list of all the turtles that has been created
Definition at line 63 of file TurtleList.java.
References simulationObjects.TurtleList.turtles.
List<Turtle> simulationObjects.TurtleList.getStamps ()
get the list of stamp made by the stamp function
Returns
list of stamps made
Definition at line 130 of file TurtleList.java.
References simulationObjects.TurtleList.stamps.
Turtle simulationObjects.TurtleList.getTurtle (int index)
get a turtle from the list of turtles that is created by the index specified
Parameters
index
Returns
the turtle at index
Definition at line 45 of file TurtleList.java.
int simulationObjects.TurtleList.getTurtleIndex (Turtle t)
get the index of a turtle in the list of all the turtles created when providing the turtle
Parameters
turtle
Returns
index
Definition at line 141 of file TurtleList.java.
Referenced by simulationObjects.TurtleList.getActiveTurtleIndexes().
void simulationObjects.TurtleList.init () throws Exception protected
Definition at line 15 of file TurtleList.java.
References simulationObjects.TurtleList.addActiveTurtle(), and simulationObjects.TurtleList.createTurtle().
void simulationObjects.TurtleList.removeTurtle (int index)
remove a turtle from the list of turtle based on the index specified
Parameters
index
Definition at line 54 of file TurtleList.java.
boolean simulationObjects.TurtleList.setActiveTurtles (int[] indexes)
locate in the list of all the turtles created to get the turtles indicated by the list of indexes that needed to be added to the active list of turtles
Parameters
indexes
Returns
boolean
Definition at line 84 of file TurtleList.java.
Member Data Documentation
List<Turtle> simulationObjects.TurtleList.activeTurtles protected
Definition at line 12 of file TurtleList.java.
Referenced by simulationObjects.TurtleList.getActiveTurtles().
List<Turtle> simulationObjects.TurtleList.stamps protected
Definition at line 13 of file TurtleList.java.
Referenced by simulationObjects.TurtleList.getStamps().
List<Turtle> simulationObjects.TurtleList.turtles protected
variable that belong to the model
Definition at line 11 of file TurtleList.java.
Referenced by simulationObjects.TurtleList.getAllTurtles().
The documentation for this class was generated from the following file:
/tmp/git/duke-compsci308-fall2014/slogo_team05/repository/src/simulationObjects/TurtleList.java